### ISSUE TITLE
Crash on IOS

### ISSUE THREAD

**Issue by matze10000** [6d7a/quito#3]
**Describe the bug**
The IOS version crashes when a username is specified:  "Could not cast value of type 'NSTaggedPointerString' (0x1f6b9bfd8) to 'NSDictionary' (0x1f6ba0400)"

in MqttOptions.swift line 29:

    if let willmsg = optionsFromJs["username"] as! NSDictionary? {
        self.will = Will(fromJsWill: willmsg)
    } else {
        self.will = nil
    }

**To Reproduce**
IOS with username in options

**Version**
v0.1.1

**Smartphone :**
Iphone 6s Plus, IOS 15.6

**Additional context**
Thanks for the nice library, on the topic of native MQTT there is unfortunately not much :-)

**Comment by 6d7a** [comment]
@matze10000 thanks for filing. I pushed an update that should resolve the issue.
