### ISSUE TITLE
bug : IOS crash when trying to connect

### ISSUE THREAD

**Issue by itweb62** [6d7a/quito#4]
i have tried in android simulator it's good.

But when i try on IOS i got no error / exception.

it's seem it's broken (IOS 13 deploy, XCODE 14.0  , CocoaPods 1.11.3 , React native 0.70.5 , React 18.1.0 ) (with expo eject build )
i have tried both TCP / TLS 

Here all my build no error appear and it's running properly except after it try to connecting..

CocoaPods Debug : 
Downloading dependencies
Installing ASN1Decoder (1.8.0)
Installing BoringSSL-GRPC (0.0.24)
Installing CocoaAsyncSocket (7.6.5)
Installing CocoaMQTT (2.0.5)
Installing DoubleConversion (1.1.6)
Installing EASClient (0.4.1) ....
Installing quito (0.1.3) ...

I use developpement build with remote debug. 
Can you please help me for knowing why my app crash ? 

#Edit

I think it was just the React-native version of the package.json . cause i have change it and it's doesn't crash.. (Expo SDK 47)
need to downgrade this version if doesn't work. 
So it's not a bug just version missmatch ^^

Thank you.
Best regards

**Comment by KevinCYM** [comment]
CocoaMQTT 2.0.6 has fixed CocoaAsyncSocket bugs on iOS 16
